name: Tests

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "LICENSE"
      - "README.md"
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: 1.21.x

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          lfs: true
          fetch-depth: 0 #for better blame info

      - name: Tests and coverage
        run: go run mage.go test

      - name: Generate content
        run: go run mage.go generate

      - name: Verifies differences
        run: git diff --exit-code

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: npm install

      - name: Build
        run: hugo --minify
